### ISSUE TITLE
test devnet

### ISSUE THREAD

**Issue by PrivetPoka33** [sarhugo/vue-candy-machine-ui#1]
I ran into this problem when I tested it on devnet.
when starting the candy machine on the local network everything works fine, but when it works on hosting after connecting the wallet, an empty field appears
![photo_2022-06-24_09-33-44](https://user-images.githubusercontent.com/107416547/175464708-ed4d4301-9306-44ee-93ca-b16bd7b738d5.jpg)

**Comment by sarhugo** [comment]
Did you set the CM address at .env? please check inspector console for errors, it seems that it can't load the candy machine

**Comment by sarhugo** [comment]
Checking https://plzz.vercel.app/ you have xxxx as CANDY_MACHINE_ID, please configure the right one at .env and it should work
